version: "3"

includes:
  train:
    taskfile: packages/aitraf-train/Taskfile.yml
    dir: .
  api:
    taskfile: packages/aitraf-api/Taskfile.yml
    dir: .

tasks:

  install:
    desc: Install workspace dependencies
    cmds:
      - uv sync

  lint:
    desc: Run ruff linting
    cmds: 
      - uv run ruff check . {{.CLI_ARGS}}

  format:
    desc: Run ruff formatting 
    cmds: 
      - uv run ruff format . {{.CLI_ARGS}}
