name: video_mae_temporal_fusion
backbone: MCG-NJU/videomae-base
model_cache_dir: ${paths.models_dir}/${.name}_cache
freeze_backbone: false
device: cuda
epochs: 25
learning_rate: 5e-5
sample_frames: 16
num_clips: 6
train_sampling_dist: uniform
eval_sampling_dist: uniform
fusion_layers: 2
fusion_heads: 8
fusion_dropout: 0.2
batch_size: 4
num_workers: 4
early_stopping_patience: 4
