backbone: MCG-NJU/videomae-base
manifests_dir: ${paths.manifests_dir}
experiment_name: aitraf_video_mae
sample_frames: 16
device: cuda
batch_size: 4
num_workers: 4
run_name: base_test

training:
  freeze_backbone: False
  run_name: train_${..run_name}
  epochs: 10
  max_train_samples: null
  output_dir: ${paths.project_root}/runs/video_mae_train

evaluation:
  run_name: eval_${..run_name}
  model_uri: null # models:/model_id
  output_dir: ${paths.project_root}/runs/video_mae_eval
