paths:
  project_root: ${hydra:runtime.cwd}
  storage_path: ${oc.env:AITRAF_STORAGE_PATH,${paths.project_root}}
  data_dir: ${paths.storage_path}/data
  manifests_dir: ${paths.data_dir}/manifests
  poses_dir: ${paths.data_dir}/poses
  boxes_dir: ${paths.data_dir}/boxes
  models_dir: ${paths.storage_path}/models
  runs_dir: ${paths.storage_path}/runs

hydra:
  run:
    dir: ${paths.runs_dir}/hydra/${now:%Y%m%d-%H%M%S}
