defaults:
  - label_studio: default
  - manifests: default
  - _self_

seed: 1337
backbone: OpenGVLab/VideoMAEv2-Base

tasks:
  pull_ls: true
  build_manifests: true

paths:
  project_root: ${hydra:runtime.cwd}
  data_dir: ${paths.project_root}/data
  manifests_dir: ${paths.data_dir}/manifests

hydra:
  run:
    dir: ${paths.data_dir}/hydra/${now:%Y%m%d-%H%M%S}
