defaults:
  - data: default
  - _self_

backbone: OpenGVLab/VideoMAEv2-Base

paths:
  project_root: ${hydra:runtime.cwd}
  data_dir: ${paths.project_root}/data
  manifests_dir: ${paths.data_dir}/manifests

hydra:
  run:
    dir: ${paths.data_dir}/hydra/${now:%Y%m%d-%H%M%S}
