defaults:
  - base
  - task@create_manifests.tasks.score_prediction: score_prediction
  - task@create_manifests.tasks.trick_classification: trick_classification
  - _self_

download_labels:
  enabled: true
  force: true
  output_path: ${paths.data_dir}/labels.jsonl

create_manifests:
  enabled: true
  force: true
  input_path: ${download_labels.output_path}
  output_dir: ${paths.manifests_dir}
  val_ratio: 0.1
  test_ratio: 0.1

download_clips:
  enabled: true
  force: false
  labels_path: ${download_labels.output_path}
  output_dir: ${paths.data_dir}/clips

download_ranks:
  enabled: true
  force: true
  prefix: ranks
  output_path: ${paths.data_dir}/ranks.jsonl

pose_and_bbox_extraction:
  enabled: true
  force: false
  limit: null
  clips_dir: ${download_clips.output_dir}
  poses_dir: ${paths.poses_dir}
  boxes_dir: ${paths.boxes_dir}
  weights_path: ${paths.models_dir}/yolo11n-pose.pt
  device: cuda
  imgsz: 640
  conf: 0.5
  batch_size: 128
  max_det: 1
