defaults:
- base
- model: ???
- task: ???
- _self_


experiment_name: aitraf_${task.name}
name: ${model.name}
run_name: eval_${name}
output_dir: ${paths.runs_dir}/${run_name}
model_id: ???
top_k_worst: 5
