defaults:
  - base
  - _self_

label_ops:
  download_labels:
    enabled: true
    force: true
    prefix: labels
    output_path: ${paths.data_dir}/labels.jsonl
  create_pairs:
    enabled: true
    force: false
    labels_path: ${label_ops.download_labels.output_path}
    output_dir: ${paths.data_dir}/pairs
    k_per_video: 3
  upload_pairs:
    enabled: true
    force: false
    prefix: pairs
    pairs_dir: ${label_ops.create_pairs.output_dir}
