defaults:
- base
- model: ???
- task: ???
- _self_


experiment_name: aitraf_${task.name}
name: ${model.name}
train_run_name: train_${name}
eval_run_name: eval_${name}
train_output_dir: ${paths.runs_dir}/${train_run_name}
eval_output_dir: ${paths.runs_dir}/${eval_run_name}
max_samples: null
top_k_worst: null
