defaults:
- base
- model: video_mae
- task: trick_classification
- _self_

experiment_name: aitraf_${task.name}
run_name: train_${model.name}
output_dir: ${paths.runs_dir}/${run_name}
max_samples: null